#!/usr/bin/env bash
# This file is generated by install-macos.sh and should not be committed to git
exec "/Users/jonasneves/Documents/GitHub/serverless-llm/venv/bin/python" "/Users/jonasneves/Documents/GitHub/serverless-llm/app/chat-interface/playground-app/native-host/serverless_llm_native_host.py" "$@"
