#!/usr/bin/env python3
"""
Sync the model table in README.md from config/models.py.
Replaces the block between the BEGIN/END MODELS markers.
Run via: make sync-readme
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from config.models import get_inference_models

readme_path = Path(__file__).parent.parent / 'README.md'

rows = [
    "| # | Model | Class | Highlights |",
    "|:--|:------|:------|:-----------|",
]
for m in get_inference_models():
    rows.append(
        f"| {m.rank} | **{m.display_name}** | {m.category.value} | {m.description or ''} |"
    )
table = '\n'.join(rows)

begin = '<!-- BEGIN MODELS (generated by `make sync-readme` — edit config/models.py, not here) -->'
end = '<!-- END MODELS -->'
new_block = f"{begin}\n{table}\n{end}"

readme_text = readme_path.read_text()
updated, n = re.subn(
    re.escape(begin) + r'[\s\S]*?' + re.escape(end),
    new_block,
    readme_text,
)
if n == 0:
    print('README.md is missing the BEGIN/END MODELS markers', file=sys.stderr)
    sys.exit(1)

if updated == readme_text:
    print('README.md model table is already up to date')
    sys.exit(0)

readme_path.write_text(updated)
print(f'Updated README.md model table ({len(get_inference_models())} models)')
