name: Inference
run-name: "${{ inputs.model }}"
'on':
  workflow_dispatch:
    inputs:
      model:
        description: Model to run
        required: true
        type: choice
        options:
        - agentcpm
        - dasd
        - functiongemma
        - gemma
        - gptoss
        - jancode
        - lfm2
        - lfm2thinking
        - llama
        - mistral
        - nanbeige
        - phi
        - qwen
        - r1qwen
        - rnj
        - smollm3
permissions:
  actions: write
  contents: read
  packages: read
jobs:
  inference:
    name: "${{ inputs.model }}"
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/inference
        with:
          model_name: ${{ inputs.model }}
          workflow_file: inference.yml
          duration_hours: '5'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          hf_token: ${{ secrets.HF_TOKEN }}
          tunnel_write_key: ${{ secrets.TUNNEL_WRITE_KEY }}
